#
# Copyright (c) 2012-2019 Kris Jusiak (kris at jusiak dot net)
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
version: di.{build}
clone_folder: c:\di
shallow_clone: true

branches:
  except:
  - benchmarks
  - gh-pages

cache:
  - C:\tools\mingw64                             -> .appveyor.yml
  - C:\Program Files (x86)\Dr. Memory            -> .appveyor.yml

environment:
  fast_finish: true

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    BS: cmake
    CMAKE_GENERATOR: Visual Studio 14 2015
    MEMCHECK: DRMEMORY
    PLATFORM: amd64
    CXX_STANDARD: 14

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
    BS: cmake
    CMAKE_GENERATOR: Visual Studio 15 2017
    MEMCHECK: DRMEMORY
    PLATFORM: amd64
    CXX_STANDARD: 14

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
    BS: cmake
    CMAKE_GENERATOR: Visual Studio 15 2017
    MEMCHECK: DRMEMORY
    PLATFORM: amd64
    CXX_STANDARD: 17

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build
    BS: cmake
    CMAKE_GENERATOR: Visual Studio 16 2019
    MEMCHECK: DRMEMORY
    PLATFORM: amd64
    CXX_STANDARD: 14

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build
    BS: cmake
    CMAKE_GENERATOR: Visual Studio 16 2019
    MEMCHECK: DRMEMORY
    PLATFORM: amd64
    CXX_STANDARD: 17

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build
    BS: cmake
    CMAKE_GENERATOR: Visual Studio 16 2019
    MEMCHECK: DRMEMORY
    PLATFORM: amd64
    CXX_STANDARD: 20

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build
    BS: cmake
    CMAKE_GENERATOR: Visual Studio 16 2019
    MEMCHECK: DRMEMORY
    PLATFORM: amd64
    CXX_STANDARD: 14

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build
    BS: cmake
    CMAKE_GENERATOR: Visual Studio 16 2019
    MEMCHECK: DRMEMORY
    PLATFORM: amd64
    CXX_STANDARD: 17

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build
    BS: cmake
    CMAKE_GENERATOR: Visual Studio 16 2019
    MEMCHECK: DRMEMORY
    PLATFORM: amd64
    CXX_STANDARD: 20

matrix:
  fast_finish: true

install:
  - cinst -y mingw drmemory
  - refreshenv
  - call "%VSPATH%"\vcvarsall %PLATFORM%

build_script:
  - mingw32-make all
