#
# Copyright (c) 2012-2016 Krzysztof Jusiak (krzysztof at jusiak dot net)
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
version: 1.0.{build}
clone_folder: c:\di
shallow_clone: true

branches:
  except:
  - benchmarks
  - gh-pages

cache:
  - C:\cmake-3.7.2-win32-x86

environment:
  fast_finish: true

  matrix:
  - platform: x64
    image: Previous Visual Studio 2015
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    BS: cmake
    MEMCHECK: DRMEMORY

  - platform: x64
    image: Visual Studio 2015
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    BS: cmake
    MEMCHECK: DRMEMORY

  - platform: x64
    image: Visual Studio 2017 RC
    VSPATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC
    BS: cmake
    MEMCHECK: DRMEMORY

matrix:
  fast_finish: true

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.7.2-win32-x86\bin\cmake.exe")) {
        pushd c:\
        Start-FileDownload 'https://cmake.org/files/v3.7/cmake-3.7.2-win32-x86.zip'
        7z x -y cmake-3.7.2-win32-x86.zip
        popd
      }
  - cinst -y drmemory
  - appveyor DownloadFile http://downloads.sourceforge.net/mingw-w64/x86_64-5.2.0-release-posix-seh-rt_v4-rev1.7z
  - 7z x x86_64-5.2.0-release-posix-seh-rt_v4-rev1.7z > nul
  - cd "%VSPATH%" && vcvarsall.bat %PLATFORM%
  - set PATH=C:\cmake-3.7.2-win32-x86\bin;mingw64\bin;%PATH%;

build_script:
  - mingw32-make all
