copyright: Copyright &copy; 2012-2018 Kris Jusiak (kris at jusiak net)
site_name: "[Boost].DI"
site_url: http://boost-experimental.github.io/di
site_author: Kris Jusiak
repo_url: https://github.com/boost-experimental/di
repo_name: di
docs_dir: .
use_directory_urls: false
theme_dir: themes/boost-experimental
google_analytics: ['UA-73083568-1', 'auto']
extra_javascript: []
extra_css: []

pages:
- Introduction: index.md
- Overview: overview.md
- Tutorial: tutorial.md
- Try It Online!: try_it.md
- Benchmarks: benchmarks.md
- User Guide: user_guide.md
- Examples: examples.md
- Extensions: extensions.md
- FAQ: FAQ.md
- CHANGELOG: CHANGELOG.md
